### ISSUE TITLE
Question for importing ppm image files

### ISSUE THREAD

**Issue by jakeoung** [ClementPinard/FlowNetTorch#1]
Thanks for sharing this code. I wonder how to load ppm images in FlyingChair dataset.

I am now trying to implement in Tensorflow, but the result of my code is bad. Do you obtain a reasonable result from this code?

**Comment by ClementPinard** [comment]
Hello, thanks for your comment.
In torch PPM images can be loaded just like any other image with image package and the function `image.load(path)`. You can still explicitly mention the type with `image.loadPPM(path)`

for tensorflow, i think you can try PIL : http://pillow.readthedocs.io/en/3.1.x/handbook/image-file-formats.html?highlight=ppm

As for the results, It has not been tested on Kitti or Sintel (the two datasets the original paper measure its quality), but you can test subjective quality with live demo, and can compare to the pretrained networks. I'm happy enough with the result. If you want to test it on Kitti and get a proper quality index, feel free ! :)

Now keep in mind that these are just the results for FlowNetS, which is far from the best they could achieve with [FlowNetS+ft+v](http://sintel.is.tue.mpg.de/hero?flow_type=Flow&method_id=531&metric_id=0&selected_pass=0)
