### ISSUE TITLE
loadcaffe [type Deconvolutoin] [type Concat] not found

### ISSUE THREAD

**Issue by Yijunmaverick** [ClementPinard/FlowNetTorch#14]
Hello I have a question about using loadcaffe_FlowNet.lua 

When I load the flownet caffemodel, there are no modules like "deconv", "Concat" in torch. How do you transfer the caffemodel to torch successfully?

Thanks

**Comment by ClementPinard** [comment]
You need to use a modified version of loadcaffe. this committed version can load deconvolution layers : https://github.com/szagoruyko/loadcaffe/pull/75
you need to clone it frome here : https://github.com/paulineluc/loadcaffe , rename `myloadcaffe-1.0-0.rockspec` to `loadcaffe-1.0-0.rockspec` and type
`luarocks make`
to install this particular version that converts Deconvolutions to SpatialFullConvolutions
