### ISSUE TITLE
Exellent work! Could you please provide a copy of file 'FlyingChairs_release.list' please?

### ISSUE THREAD

**Issue by yxqlwl** [ClementPinard/FlowNetTorch#2]
Exellent work! Could you please provide a copy of file 'FlyingChairs_release.list' please?

**Comment by ClementPinard** [comment]
Hello ! Apparently they updated their dataset, removing the list file. It's understandable, as it only listed the file like that : 
`FlyingChairs_release/data/n_img1.ppm	FlyingChairs_release/data/n_img2.ppm	FlyingChairs_release/data/n_flow.flo`
with `n` going from 00001 to 22872

My dataset was outdated, so I'm preparing a commit to handle this case (should be quick)

**Comment by ClementPinard** [comment]
Done, and my backup list file is avalaible [here](https://drive.google.com/open?id=0B5EC7HMbyk3COEVEZ1VETzhhMnc) if you still want to use it.
let me know how it works for you!

Clément

**Comment by yxqlwl** [comment]
Sorry for the delay due to some problems in torch installation. It works. Thanks!
