### ISSUE TITLE
Hi, a problem about FlownetS.lua

### ISSUE THREAD

**Issue by yxqlwl** [ClementPinard/FlowNetTorch#5]
Hi, according to the network definition of FlowNetS in 《FlowNet: Learning Optical Flow with Convolutional Networks》，maybe conv4_1 in FlownetS.lua( and FlownetSBN.lua ) is supposed to be like the following?

     conv4_1:add(nn.SpatialConvolution(256,512,3,3,2,2,1,1))
     conv4_1:add(nn.LeakyReLU(0.1,true))
     conv4_1:add(nn.SpatialConvolution(512,512,3,3,1,1,1,1))
     conv4_1:add(nn.LeakyReLU(0.1,true))

Thanks!

**Comment by ClementPinard** [comment]
You are right. I changed the specifications to match the original paper. Thank you for noticing it !
However, i am not planning to redo the graphs in the README, so they may be different from the 'official' architecture.

Clément

**Comment by yxqlwl** [comment]
Just a small mistake:)On the whole, this code is exellent.
