### ISSUE TITLE
Hi, about the number of iterations

### ISSUE THREAD

**Issue by yxqlwl** [ClementPinard/FlowNetTorch#6]
Hi,
         I also studied the caffe based flownet code maintained by the authors. With batch_size =8, the number of iterations of this code(2573*55~=140K) is about 1/4 of that of the original code(600K iterations)? Maybe more accurate results can be obtained with the same number of iterations as flownet caffe?
Thanks!

**Comment by ClementPinard** [comment]
Hello, just tried for FlowNetS pretrained inference results, and it's about 2.0 EPE which is slightly better than our network, so you're right, we might be able to do some improvement (especially from the model modification you suggested some days ago that made the model wider)
I just began a training with 230 epochs, trying to match caffe hyperparameters, will keep you updated with the results.

**Comment by yxqlwl** [comment]
Nice!
Thanks!
